### PR TITLE
Added proxy support

### PR DESCRIPTION
**Pull request by otlie**
Added a `proxy` kwarg to __init\__() and added an if condition to update session headers w/ specified proxy. See #96

### CODE REVIEW

**Comment by kovacsbalu** [comment]
"Note that only HTTPS proxies work with Pushbullet" can you please modify your code to setup only https proxy?

**Comment by otlie** [comment]
@kovacsbalu Done. Requests will automatically use the HTTPS proxy if suitable, therefore it doesn't matter if they had a non-http along side the HTTPS, it'll still use the HTTPS.

**Comment by troeggla** [comment]
I wonder if the dictionary syntax like [here](https://github.com/randomchars/pushbullet.py/pull/102/files#diff-4fca3e8b2a5097bd09e6e331b570ade8R73) in the example is necessary if only HTTPS proxies are allowed anyway. Or is there a rationale behind this?

**Comment by simonporter007** [comment]
Out of interest, where does the HTTPS proxy only requirement come from?

**Comment by otlie** [comment]
@troeggla: It's explicit, there's multiple types of proxies (SOCKS, HTTP(S)).

@simonporter007: The API will return a `This server is only accessible over HTTPS.' message if you try to access the API using HTTP. 

``{"error":{"code":"invalid_request","type":"invalid_request","message":"This server is only accessible over HTTPS.","cat":"(=^‥^=)"},"error_code":"invalid_request"}``

**Comment by troeggla** [comment]
Ah I understand, that makes sense! If there are no more concerns, I will merge this.

**Comment by simonporter007** [comment]
Right sorry, misunderstood. You can use both http and https proxy addresses but you have to connect to the https endpoint (quite rightly).

Then maybe it does make sense to remove the dictionary syntax? As whatever is passed in should be handed to the https key?

```
curl --proxy http://proxy.com:8080 --header 'Access-Token: xxxxxxxxxxxxxxxxxxxxxxx' https://api.pushbullet.com/v2/users/me -k
{"active":true,"iden":"xxxxxxxxxxxxx","created":1.41617401377777e+09,"modified":1.479242967034234e+09,......}
```
```
curl --proxy http://proxy.com:8080 --header 'Access-Token: xxxxxxxxxxxxxxxxxxxxxxx' http://api.pushbullet.com/v2/users/me -k
{"error":{"code":"invalid_request","type":"invalid_request","message":"This server is only accessible over HTTPS.","cat":"(=^‥^=)"},"error_code":"invalid_request"}
```

**Comment by otlie** [comment]
@simonporter007 Well, I think the current syntax is more explicit and should be kept. As an example, it would suck if someone saw the word `proxy' with no protocol specified and bought a non-HTTP proxy (one could argue this is their own fault for not reading the documentation though), I think it would `do more good than harm'

**Comment by simonporter007** [comment]
@otlie fair point indeed!

**Pull request merged**
