### PR TITLE
Convert listener.py to asyncio and coroutines

### PR DESCRIPTION
**Pull request by rharder**
I converted listener.py to using asyncio and the websockets package.  I also added a get_new_pushes() function to pushbullet.py to retrieve only the most recent pushes.  Not sure if you want to take this package down the asyncio path, but here's a start at least.

### CODE REVIEW

**Comment by kovacsbalu** [comment]
Hi @rharder, 
thanks for you PR. Can you please fix failed check errors?

**Comment by rharder** [comment]
Yeah, I was looking at that, but I'm not sure how to interpret it.  There's
an error that says

ImportError: No module named 'websockets'

but that would have to be installed with pip install websockets.  I'll
google around and see what's up.

-Rob

**Comment by rharder** [comment]
OK, well the v2.7 test fails because asyncio and coroutines aren't supported in v2.7.  Not sure if you want to abandon v2.7 support.

**Comment by rharder** [comment]
I'm going to close this pull request.  I've done a complete conversion of pushbullet to asyncio, but I'm going to try to find an elegant way to have both regular and asyncio in the same package with a minimal amount of code duplication.

**Pull request closed without merging**
