### PR TITLE
Include tests and examples in source distributions

### PR DESCRIPTION
**Pull request by sbraz**
Hi,
It would be really nice if you could include tests and examples in the PyPI tarballs as we at Gentoo usually get the package source there.

### CODE REVIEW

**Comment by sbraz** [comment]
@troeggla Thanks! Do you plan on releasing a new version soon? 0.10.0 seems to have issues with filetypes and Python 3, I had to backport fixes from the git master to make tests pass.

**Comment by troeggla** [comment]
No problem! Thank you for your contribution. Sadly I don't have permission to create new releases on PyPI. Pinging @randomchars, because I think he's the only one that can do that.

**Comment by sbraz** [comment]
@troeggla You seem to have set up travis to deploy to PyPI so I guess you could just add the tag yourself and it would upload the new release :P

**Comment by sbraz** [comment]
@randomchars @troeggla any chance to see that new release?

**Comment by troeggla** [comment]
Not quite sure who set up Travis, because it wasn't me. Sorry about that!
@r-darwish or @kovacsbalu does any of you have access to PyPI and can create a new release?

**Comment by kovacsbalu** [comment]
@troeggla sorry I don't have access. :(

**Comment by sbraz** [comment]
Travis is set to deploy all new tags: https://github.com/randomchars/pushbullet.py/blob/master/.travis.yml#L14
All you need to do is tag a new release and it will get uploaded to PyPI.

**Pull request merged**
